
= ODISC: The Open Digital Intelligent Slot Car Racing Ecosystem

Welcome to the Open Digital Intelligent Slot Car (ODISC) documentation.

These documents define the architecture, standards, and requirements of the ODISC Racing Ecosystem.

Please select an area below to explore our framework architecture, active technical specifications, and racing rules:

== Introduction to ODISC

If you are new to ODISC and want to find out the vision and reasoning behind ODISC, you may want to start with looking at xref:why_ODISC.adoc[why ODISC exists] or maybe get an xref:intro_to_ODISC.adoc[introduction to ODISC].

== Documentation Areas

xref:principles_and_foundations:ROOT:index.adoc[ODISC Principles and Foundations]::

If want to know more about ODISC principles and governance, you want to start here.

xref:technical_specifications:ROOT:index.adoc[ODISC Technical Specifications]::

If you want to know how ODISC works, the technical requirements, or how to develop products for ODISC, then start with the technical specifications.

xref:racing_regulations:ROOT:index.adoc[Racing Regulations] - Future Content::

If you want to race within the ODISC Ecosystem, the racing regulations will tell you all about how racing classes are structured and races are managed.


xref:contributor_resources:ROOT:index.adoc[Contributor Internal Resources] - Future Content::
For authors and technical editors, please review our resource for various help and suggestions to get started building documentation, as well as expectations on formatting prior to submitting revisions.

