

= AsciiDoc Best Practices

== File Structure within the Docs folder
The following file structure is being used for the AsciiDoc files in this repository. The structure is based on the AsciiDoc best practices and the AsciiDoc file structure used in the ODISC project.

=== Modules
// TODO: Update with latest repository structure

The following modules are used by the ODISC project.

==== Asciidoc Best Practices
A list of best practices to help people get up to speed on writing documentation.

==== Root
The root module. This is the primary entry point for Ascii Docs documentation.

===== Appendices
The appendices directory contains files that provide additional information and context for the ODISC specification. The appendices directory contains the following subdirectories in alphabetical order.

====== Naming Conventions
The naming_conventions directory contains files that define the naming conventions used throughout the ODISC specification.

====== Terminology
The terminology directory contains files that define the terminology used throughout the ODISC specification.

===== Guiding Principles
The guiding_principles directory contains files that list our guiding principles used when developing the ODISC specification.

===== Introduction
This directory contains files that provide an introduction of the ODISC racing ecosystem.

===== Overview
This directory contains files that provide an overview of the ODISC racing ecosystem and is the starting point for understanding the specification. The index.adoc file incorporates the other files in this directory to provide a complete introduction to the system.

===== Technical Specifications
This directory contains files that define the technical specifications for the ODISC specification. The technical_specifications directory contains the following subdirectories in alphabetical order.

====== DS
The DS directory contains files that define the domain standards for the ODISC specification. The DS directory contains one directory for each TLS, named as TLS-??? where ??? is the TLS number. Each TLS directory contains one directory for each DS, named as DS-???-??? where the first ??? is the TLS number and the second ??? is the DS number.

====== TLS
This directory contains files that define the technical library standards for the ODISC specification. The TLS directory contains one directory for each TLS, named as TLS-??? where ??? is the TLS number. Each TLS may be broken into multiple files to make it easier to focus during editing. 

Each TLS file is named as TLS-??? Name where ??? is the TLS number and Name is a short description of the section of the TLS that is contained in it. The TLS-???_index.adoc file is the main file for the TLS and incorporates the other files in the TLS directory to provide a complete specification for that TLS.

====== [red]#PENDING# -  WAC
The WAC directory contains files that define the workshop activity categories for the ODISC specification. The WAC directory contains one directory for each WAC, named as WAC-??? where ??? is the WAC number. Each WAC may be broken into multiple files to make it easier to focus during editing.

=== Publications
The publications directory contains files that generate the finished output of the various versions of the ODISC specification. The publications directory contains the following files.

Technical Reference: `publications/technical-reference.adoc` - This file contains the technical reference for the ODISC specification. It is generated from the AsciiDoc files in the `docs` directory.

== Naming Conventions
All documents must follow the listed naming conventions above in this document. The naming conventions are designed to make it easier to find and understand the documents in the ODISC specification.


== File Contents
The following rules apply to all files that generate content for the ODISC documentation.

=== [red]*CRITICAL:* White Space
[WARNING]
====
All files [red]*must* start and end with at least 2 lines of white space to ensure that sections and headers are generated properly by AsciiDoc.

If these are not present, AsciiDoc sometimes does not properly generate section headers resulting in loss of functionality and indexing of files during generation.
====

=== Anchors
Each primary document must have an anchor at the top of the document. We define a document as primary if it is structured in a way that it can be read on its own. These are most often named "index.adoc", such as the index file in a TLS or DS.

The anchor is used to link to the document from other documents in the ODISC specification. The anchor is defined as follows.
[anchor]

==== Specific Document Patterns
For the following items, we use a consistent pattern for creating reference links. This provides the user with a consistent experience when reading documentation.

They are defined as follows:

* [#gp-???] GP Name +
where ??? is the Guiding Principal number
* [#TLS-???] TLS Name +
where ??? is the Technical Library Standard number
* [#ds-???-???] DS Name +
where the first ??? is the TLS number and the second ??? is the Domain Specification number
* [#WAC-???] WAC Name +
where ??? is the Workshop Activity Categories number

== Linking to Anchors
When linking to anchors, it is highly recommended to use the full xref syntax as follows:

* \xref:relative_path_to_file.adoc#anchorname[Link Text]


