
:doctitle: AsciiDoc Best Practices
:webtitle: {doctitle}
:webicon: /navigation/folder_group/ACTIVE_STATUS
:navtitle: Best Practices
[#contributor_resources]
= {doctitle}

== File Structure within the Docs folder
The following file structure is being used for the AsciiDoc files in this repository. The structure is based on the AsciiDoc best practices and the AsciiDoc file structure used in the ODISC project.

build:: Contains the build output. Not in source control.
docs:: Contains all documents that generate into HTML.
publications:: Contains all documents that generate into PDF. These utilize the files in `docs` for content.
resources:: Utility files that are included into the finished product in some way.
utility_scripts:: The build process and other utility scripts live here.


== File Contents
The following rules apply to all files that generate content for the ODISC documentation.

=== [red]*CRITICAL:* White Space
[WARNING]
====
All files [red]*must* start and end with at least 2 lines of white space to ensure that sections and headers are generated properly by AsciiDoc.

If these are not present, AsciiDoc sometimes does not properly generate section headers resulting in loss of functionality and indexing of files during generation.
====

=== Anchors
Each primary document must have an anchor at the top of the document. We define a document as primary if it is structured in a way that it can be read on its own. These are most often named "index.adoc", such as the index file in a TLS or DS.

The anchor is used to link to the document from other documents in the ODISC specification. The anchor is defined as follows.
[anchor]

==== Specific Document Patterns
For the following items, we use a consistent pattern for creating reference links. This provides the user with a consistent experience when reading documentation.

They are defined as follows:

* [#gp-???] GP Name +
where ??? is the Guiding Principal number
* [#TLS-???] TLS Name +
where ??? is the Technical Library Standard number
* [#ds-???-???] DS Name +
where the first ??? is the TLS number and the second ??? is the Domain Specification number
* [#WAC-???] WAC Name +
where ??? is the Workshop Activity Categories number

== Linking to Anchors
When linking to anchors, it is highly recommended to use the full xref syntax as follows:

* \xref:relative_path_to_file.adoc#anchorname[Link Text]


