
:doctitle: TLG-002 - Multi-Racetrack Venue
:webtitle: {doctitle}
:webicon: /navigation/document/STATUS
:navtitle: Multi-Racetrack Venue
[#tlg-002]
= {doctitle} Multi-Racetrack Venue

== Identification Block

[cols="2s,6",options="header"]
|===
|Field|Value
|Title| {doctitle}
|Version| 0.1
|Release Date| TBD
|Status| Draft
|Maintainer(s)| Designated Maintainer
|===

== Introduction

A multi-racetrack venue provides additional hardware and software
capabilities to allow multiple racetracks to operate in a single
location and combine their results into a championship. This allows 
for larger events, such as tournaments, to be held at a single location.

== Functional Areas

A multi-racetrack venue consists of two or more racetracks in accordance
with the Racetrack Installation (xref:../TLG-003/index.adoc#tlg-001[TLG-003]).

A multi-racetrack venue may include Venue Management capabilities as
defined by the Race Management System
(xref:../../TLS/TLS-001/index.adoc#tls-002_venue_management[TLS-002]).

Venue Management is not a requirement for a multi-racetrack venue, but is
highly recommended for managing multiple racetracks.

=== Venue Management Subsystem

The Venue Management subsystem uses the same software package and hardware
platform as the Race Management System, but requires fewer hardware
connections.


== Document Revision History

[cols="2,3,8",options="header"]
|===
| Version | Date | Description

| 0.1 
| 2026-??-?? 
| Initial Draft.

|===

